import { Inter } from "next/font/google";
import Link from "next/link";
import './layout.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='nav-container'>
          <div>
          <Link href={'/'}><p>Home</p></Link>
            </div>
            <div className="second-container">
              <div><Link href={'/photos'}>Photos</Link></div>
              <div><Link href={'/about'}>About me</Link></div>
              
              </div>          
        </div>
        {children}
        <div className="footer">Footer</div></body>
    </html>
  );
}
